runtime: python311

handlers:
- url: /
  static_files: dist/apps/arrows-ts/index.html
  upload: dist/apps/arrows-ts/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.*)
  static_files: dist/apps/arrows-ts/\1
  upload: dist/apps/arrows-ts/(.*)
  secure: always
  redirect_http_response_code: 301
