# Optional substitution: set _APP_YAML=app.staging.yaml in a trigger to deploy to staging.
# Default (production): app.yaml
substitutions:
  _APP_YAML: 'app.yaml'

steps:
- name: node:18
  entrypoint: npm
  args: ['install']

- name: node:18
  entrypoint: npm
  args: ['run', 'build']
  secretEnv: ['VITE_GOOGLE_API_KEY']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '${_APP_YAML}']

availableSecrets:
  secretManager:
  - versionName: projects/arrows-app-295615/secrets/google-api-key/versions/2
    env: 'VITE_GOOGLE_API_KEY'
