import { describe, expect, it } from 'vitest';
import { shouldRefit } from './embedViewportMiddleware';

describe('shouldRefit — embed-side decision: refit the canvas or not', () => {
  describe('actions that should NEVER refit (regression of the drag-end teleport bug)', () => {
    it('returns false for MOVE_NODES_END_DRAG (the original bug source)', () => {
      expect(shouldRefit({ type: 'MOVE_NODES_END_DRAG' }, false)).toBe(false);
      expect(shouldRefit({ type: 'MOVE_NODES_END_DRAG' }, true)).toBe(false);
    });

    it('returns false for MOVE_NODES (mid-drag — would jump every frame)', () => {
      expect(shouldRefit({ type: 'MOVE_NODES' }, true)).toBe(false);
    });

    it('returns false for node CRUD — extension users dont expect a refit', () => {
      expect(shouldRefit({ type: 'CREATE_NODE' }, true)).toBe(false);
      expect(shouldRefit({ type: 'DELETE_NODES_AND_RELATIONSHIPS' }, true)).toBe(false);
      expect(shouldRefit({ type: 'DUPLICATE_NODES_AND_RELATIONSHIPS' }, true)).toBe(false);
    });

    it('returns false for autoGenerated actions (would re-trigger itself)', () => {
      expect(shouldRefit({ type: 'WINDOW_RESIZED', autoGenerated: true }, false)).toBe(false);
      expect(shouldRefit({ type: 'GETTING_GRAPH_SUCCEEDED', autoGenerated: true }, false)).toBe(false);
    });

    it('returns false for actions with no type', () => {
      expect(shouldRefit({}, false)).toBe(false);
    });

    it('returns false for unrelated actions', () => {
      expect(shouldRefit({ type: 'ADJUST_VIEWPORT' }, true)).toBe(false);
      expect(shouldRefit({ type: 'SCROLL' }, true)).toBe(false);
      expect(shouldRefit({ type: 'SELECT_NODE' }, true)).toBe(false);
    });
  });

  describe('actions that SHOULD refit', () => {
    it('refits on WINDOW_RESIZED regardless of load state', () => {
      expect(shouldRefit({ type: 'WINDOW_RESIZED' }, false)).toBe(true);
      expect(shouldRefit({ type: 'WINDOW_RESIZED' }, true)).toBe(true);
    });

    it('refits on TOGGLE_INSPECTOR regardless of load state', () => {
      expect(shouldRefit({ type: 'TOGGLE_INSPECTOR' }, false)).toBe(true);
      expect(shouldRefit({ type: 'TOGGLE_INSPECTOR' }, true)).toBe(true);
    });
  });

  describe('initial load handling — fits once, never again', () => {
    it('refits on the first GETTING_GRAPH_SUCCEEDED (opening the file)', () => {
      expect(shouldRefit({ type: 'GETTING_GRAPH_SUCCEEDED' }, false)).toBe(true);
    });

    it('does NOT refit on subsequent GETTING_GRAPH_SUCCEEDED (host echoes after edits)', () => {
      expect(shouldRefit({ type: 'GETTING_GRAPH_SUCCEEDED' }, true)).toBe(false);
    });
  });
});
