// @ts-expect-error JS modules without local typings.
import { adjustViewport } from '../actions/viewTransformation';
// @ts-expect-error
import { computeCanvasSize } from '../model/applicationLayout';
// @ts-expect-error
import { getVisualGraph } from '../selectors';
// @ts-expect-error
import { calculateViewportTranslation } from '../middlewares/viewportMiddleware';
import type { Middleware } from 'redux';

// The web app's viewportMiddleware auto-refits the canvas on drag-end, node
// CRUD, and even mid-drag if a node moves off-canvas. In a VS Code tab where
// the user is intentionally zoomed in, every one of those re-fits feels like
// a teleport. This embed version only refits on the events the user can't
// reasonably predict — initial load, window resize, inspector toggle.

const REFIT_ACTIONS = new Set(['WINDOW_RESIZED', 'TOGGLE_INSPECTOR']);

export interface ActionShape {
  type?: string;
  autoGenerated?: boolean;
}

// Pure decision: should this action trigger a refit?
// GETTING_GRAPH_SUCCEEDED fires on initial load AND every host echo — only the
// first one means "user opened the file", subsequent ones would jump the view.
export function shouldRefit(action: ActionShape, initialLoadHandled: boolean): boolean {
  if (action.autoGenerated || !action.type) return false;
  if (action.type === 'GETTING_GRAPH_SUCCEEDED') return !initialLoadHandled;
  return REFIT_ACTIONS.has(action.type);
}

// Factory so each store gets its own initial-load flag (also makes the
// middleware testable without resorting to vi.resetModules).
export function createEmbedViewportMiddleware(): Middleware {
  let initialLoadHandled = false;
  return (store) => (next) => (action) => {
    const result = next(action);
    const a = action as ActionShape;
    if (!shouldRefit(a, initialLoadHandled)) return result;
    if (a.type === 'GETTING_GRAPH_SUCCEEDED') initialLoadHandled = true;

    const state = store.getState() as { applicationLayout: unknown };
    const canvasSize = computeCanvasSize(state.applicationLayout);
    const visualGraph = getVisualGraph(state);
    const { scale, translateVector } = calculateViewportTranslation(visualGraph, canvasSize);
    if (scale) {
      store.dispatch(adjustViewport(scale, translateVector.dx, translateVector.dy));
    }
    return result;
  };
}

export const embedViewportMiddleware = createEmbedViewportMiddleware();
