// @ts-expect-error JS modules without local typings.
import { adjustViewport } from '../actions/viewTransformation';
// @ts-expect-error
import { computeCanvasSize } from '../model/applicationLayout';
// @ts-expect-error
import { getVisualGraph } from '../selectors';
// @ts-expect-error
import { calculateViewportTranslation } from '../middlewares/viewportMiddleware';
import type { Middleware } from 'redux';

// The web app's viewportMiddleware auto-refits the canvas on drag-end, node
// CRUD, and even mid-drag if a node moves off-canvas. In a VS Code tab where
// the user is intentionally zoomed in, every one of those re-fits feels like
// a teleport. This embed version only refits on the events the user can't
// reasonably predict — initial load, window resize, inspector toggle.

const REFIT_ACTIONS = new Set([
  'WINDOW_RESIZED',
  'TOGGLE_INSPECTOR',
]);

// GETTING_GRAPH_SUCCEEDED fires on initial load AND on every host echo.
// Refit on the first one only — subsequent echoes mid-session would jump
// the view away from wherever the user is working.
let initialLoadHandled = false;

export const embedViewportMiddleware: Middleware = (store) => (next) => (action) => {
  const result = next(action);
  const a = action as { type?: string; autoGenerated?: boolean };
  if (a.autoGenerated || !a.type) return result;

  const isInitialLoad = a.type === 'GETTING_GRAPH_SUCCEEDED' && !initialLoadHandled;
  if (isInitialLoad) initialLoadHandled = true;

  if (!isInitialLoad && !REFIT_ACTIONS.has(a.type)) return result;

  const state = store.getState() as { applicationLayout: unknown };
  const canvasSize = computeCanvasSize(state.applicationLayout);
  const visualGraph = getVisualGraph(state);
  const { scale, translateVector } = calculateViewportTranslation(visualGraph, canvasSize);
  if (scale) {
    store.dispatch(adjustViewport(scale, translateVector.dx, translateVector.dy));
  }
  return result;
};
