// @ts-expect-error JS modules without local typings.
import { adjustViewport } from '../actions/viewTransformation';
// @ts-expect-error JS module without local typings.
import { computeCanvasSize } from '../model/applicationLayout';
// @ts-expect-error JS module without local typings.
import { getVisualGraph } from '../selectors';
// @ts-expect-error JS module without local typings.
import { calculateViewportTranslation } from '../middlewares/viewportMiddleware';
import type { Middleware } from 'redux';

// Replaces the web app's auto-refit-on-everything with refit-on-unpredictable-events
// (load, resize, inspector toggle). Anything else would teleport the user's view.

const REFIT_ACTIONS = new Set(['WINDOW_RESIZED', 'TOGGLE_INSPECTOR']);

export interface ActionShape {
  type?: string;
  autoGenerated?: boolean;
}

export function shouldRefit(action: ActionShape, initialLoadHandled: boolean): boolean {
  if (action.autoGenerated || !action.type) return false;
  // GETTING_GRAPH_SUCCEEDED fires on first load AND host echoes; only refit once.
  if (action.type === 'GETTING_GRAPH_SUCCEEDED') return !initialLoadHandled;
  return REFIT_ACTIONS.has(action.type);
}

export function createEmbedViewportMiddleware(): Middleware {
  let initialLoadHandled = false;
  return (store) => (next) => (action) => {
    const result = next(action);
    const a = action as ActionShape;
    if (!shouldRefit(a, initialLoadHandled)) return result;
    if (a.type === 'GETTING_GRAPH_SUCCEEDED') initialLoadHandled = true;

    const state = store.getState() as { applicationLayout: unknown };
    const canvasSize = computeCanvasSize(state.applicationLayout);
    const visualGraph = getVisualGraph(state);
    const { scale, translateVector } = calculateViewportTranslation(visualGraph, canvasSize);
    if (scale) {
      store.dispatch(adjustViewport(scale, translateVector.dx, translateVector.dy));
    }
    return result;
  };
}

export const embedViewportMiddleware = createEmbedViewportMiddleware();
