import { describe, expect, it } from 'vitest';
import { shouldRefit } from './embedViewportMiddleware';

describe('shouldRefit - refit decision per action type', () => {
  // [action, initialLoadHandled, expected]
  const cases: Array<[Parameters<typeof shouldRefit>[0], boolean, boolean]> = [
    // never refit - would teleport the user's view
    [{ type: 'MOVE_NODES_END_DRAG' }, true, false],
    [{ type: 'MOVE_NODES' }, true, false],
    [{ type: 'CREATE_NODE' }, true, false],
    [{ type: 'DELETE_NODES_AND_RELATIONSHIPS' }, true, false],
    [{ type: 'DUPLICATE_NODES_AND_RELATIONSHIPS' }, true, false],
    [{ type: 'ADJUST_VIEWPORT' }, true, false],
    [{ type: 'SCROLL' }, true, false],
    [{ type: 'SELECT_NODE' }, true, false],
    [{}, false, false],
    // autoGenerated guards against self-trigger loops
    [{ type: 'WINDOW_RESIZED', autoGenerated: true }, false, false],
    [{ type: 'GETTING_GRAPH_SUCCEEDED', autoGenerated: true }, false, false],
    // always refit - canvas dimensions or viewport changed unpredictably
    [{ type: 'WINDOW_RESIZED' }, false, true],
    [{ type: 'WINDOW_RESIZED' }, true, true],
    [{ type: 'TOGGLE_INSPECTOR' }, false, true],
    [{ type: 'TOGGLE_INSPECTOR' }, true, true],
    // initial load: fit on first GETTING_GRAPH_SUCCEEDED, ignore subsequent echoes
    [{ type: 'GETTING_GRAPH_SUCCEEDED' }, false, true],
    [{ type: 'GETTING_GRAPH_SUCCEEDED' }, true, false],
  ];

  it.each(cases)('%j (loaded=%s) → %s', (action, loaded, expected) => {
    expect(shouldRefit(action, loaded)).toBe(expected);
  });
});
